# TODO: Envtually there will be a command interface option.
#       This is good for now, as it makes the development process
#       go a little smoother...

# Basic cutout search parameters
cutouts:
    # list of csv files of ra-dec's.
    ra_dec_deg_csv_files:
        #- BH12_120RA180_minus4DEC16_RC4_targetlist.csv
        #- BH12_multicomponent_zlt0p05_targetlist2.csv
        #- targs_for_michelle.csv
        #- wise_mosaicing_debuging.csv
        - vlass_mosaicing_debuging.csv
        #~- cluster_radio.csv # 2.5'

    # Note: box size in csv's overidde this one.
    #box_size_armin: 3
    #box_size_armin: 5
    box_size_armin: 2.5
    
    # ClaRAN: Requires, FIRST, VLASS, WISE, and PanSTARRS.
    surveys:
        #- FIRST      # Faint Images of the Radio Sky at Twenty-Centimeters
        - NVSS
        #- VLASS:     # * claran
        # TODO: Debug mosaicing for WISE
        #   - J105915+051731_s3arcmin_WISE-w1.fits
        #   - (RA,Dec) = (164.811020,+5.292027)
        # TODO: I believe above is fixed now! Wait for validation.
        #- WISE:      # * claran
        #      filters: w1
        #- PanSTARRS: # * claran
        #      # TODO: Make it handle cases like i,z instead of [i,z]
        #      filters: i 
        #- SDSS:
        #      filters: [g,r,i]

# TODO: Implement below...
# Processing output paramters
configuration:
    # data root relative/absolute path defn
    # Note: all output is put under a "data" at data_root.
    # NB: The "data" dir is in .gitignore.
    data_root: .

    flush: True

    force_overwrite: True

