# Basic cutout search parameters
cutouts:
    ra_dec_deg_csv_files:
        #- BH12_120RA180_minus4DEC16_RC4_targetlist.csv
        #- BH12_multicomponent_zlt0p05_targetlist2.csv
        - targs_for_michelle.csv

    # Note: box sizes in csv's overidde this one.
    box_size_arcmin: 5
    
    surveys:
        - VLASS

# Processing output parameters
configuration:
    # data root relative/absolute path defn
    local_root: data/vlass_s5a_debug
