# CLARAN -- SAMPLE FILE
# => Adjust to taste

# Basic cutout search parameters
cutouts:
    # list of csv files of ra-dec's.
    ra_dec_deg_csv_files:
        #- BH12_120RA180_minus4DEC16_RC4_targetlist.csv
        #- BH12_multicomponent_zlt0p05_targetlist2.csv
        - targs_for_michelle.csv

    # Note: box size in csv's overidde this one.
    box_size_armin: 3
    
    surveys:
        - FIRST
        - VLASS
        - WISE:
              filters: [w1]
        - PanSTARRS:
              filters: [i]

# Processing output parameters
configuration:
    # data root relative/absolute path defn
    data_root: data/claran
