# TODO: Envtually there will be a command interface option.
#       This is good for now, as it makes the development process
#       go a little smoother...

# Basic cutout search parameters
cutouts:
    # list of csv files of ra-dec's.
    ra_deg_deg_csv_files:
        #- BH12_120RA180_minus4DEC16_RC4_targetlist.csv
        #- BH12_multicomponent_zlt0p05_targetlist2.csv
        - targs_for_michelle.csv

    # Note: box size in csv's overidde this one.
    box_size_armin: 5
    
    surveys:
        - FIRST
        - NVSS
        - VLASS:
              bart: home
              filters: foo # TODO: fix case when 'foo' is missing for SurveyConfig::get_filters()
        - WISE:
              filters: w1
        - PanSTARRS:
              filters: [i,k]
        - SDss:
              filters: [g,r,i]

# TODO: Implement below...
# Processing output paramters
configuration:
    # Note: all output is put under a "data" at data_root.
    # NB: The "data" dir is in .gitignore.
    data_root: .

    flush: True

    force_overwrite: True

