# Basic cutout search parameters
cutouts:
    # list of csv files of ra-dec's.
    ra_dec_deg_csv_files:
        - changes.csv

    # Note: box size in csv's overidde this one.
    #box_size_armin: 11.53
    box_size_armin: 30.0
    
    surveys:
        - VLASS

# Processing output parameters
configuration:
    # data root relative/absolute path defn
    local_root: data/changes
