# TODO (Issue #14): Envtually there will be a command interface option.
#       This is good for now, as it makes the development process
#       go a little smoother...

# Basic cutout search parameters
cutouts:
    # list of csv files of ra-dec's.
    ra_dec_deg_csv_files:
        #- BH12_120RA180_minus4DEC16_RC4_targetlist.csv
        #- BH12_multicomponent_zlt0p05_targetlist2.csv
        - targs_for_michelle.csv
        #- wise_mosaicing_debuging.csv
        #- vlass_mosaicing_debuging.csv
        #~- cluster_radio.csv # 2.5'

    # Note: box size in csv's overidde this one.
    box_size_arcmin: 3
    #box_size_arcmin: 5
    #box_size_arcmin: 2.5
    
    # ClaRAN: Requires, FIRST, VLASS, WISE, and PanSTARRS.
    surveys:
        #- FIRST      # Faint Images of the Radio Sky at Twenty-Centimeters
        #- NVSS
        #- VLASS:     # * claran
        # TODO (Issue #12): Debug mosaicing for WISE
        #   - J105915+051731_s3arcmin_WISE-w1.fits
        #   - (RA,Dec) = (164.811020,+5.292027)
        # TODO (Issue #12): I believe above is fixed now! Wait for validation.
        - WISE:      # * claran
              filters: w1
        - PanSTARRS: # * claran
              # TODO (Issue #13): Make it handle cases like i,z instead of [i,z]
              filters: i
        - SDSS:
              filters: [g,r,i]

# Processing output parameters
configuration:
    # data root relative/absolute path defn
    local_root: data/debug

    # remote vospace workspace root
    remote_root: cutout_testing/debug

    # TODO (Issue #13): Implement
    flush: True

    # TODO (Issue #13): Implement
    force_overwrite: True

