# Basic cutout search parameters
cutouts:
    ra_deg_deg_csv_files:
        #- BH12_120RA180_minus4DEC16_RC4_targetlist.csv
        #- BH12_multicomponent_zlt0p05_targetlist2.csv
        - targs_for_michelle.csv

    # Note: box sizes in csv's overidde this one.
    box_size_armin: 7
    
    surveys:
        - VLASS

