# Basic cutout search parameters
cutouts:
    # list of csv files of ra-dec's.
    ra_dec_deg_csv_files:
        #- BH12_120RA180_minus4DEC16_RC4_targetlist.csv
        #- BH12_multicomponent_zlt0p05_targetlist2.csv
        #- targs_for_michelle.csv
        - panstarrs_debug.csv

    # Note: box size in csv's overidde this one.
    box_size_arcmin: 3
    
    surveys:
        - FIRST
        - NVSS
        - VLASS
        - WISE:
              filters: w1
        - PanSTARRS:
              filters: [i]
        - SDSS:
              filters: [g,r,i]

# Processing output parameters
configuration:
    # data root relative/absolute path defn
    local_root: data/out

    # overwrite existing files on download
    overwrite: False

    # flush files before downloading (superceeds overwrite)
    flush: True
